name: donate_life
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  lottie: ^2.3.0
  intl_phone_number_input: ^0.7.2

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins_Regular.ttf
        - asset: assets/fonts/Poppins/Poppins_Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins_Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins_Light.ttf
          weight: 300

    - family: Times New Roman
      fonts:
        - asset: assets/fonts/Times_New_Roman/times_new_roman_bold.ttf
          weight: 700
        - asset: assets/fonts/Times_New_Roman/times_new_roman_italic.ttf
          style: italic
        - asset: assets/fonts/Times_New_Roman/times_new_roman.ttf
